### ISSUE TITLE
Ajouter à l’application principale un menu « Applications » comportant 8 items permettant de lancer la résolution de ces exercices et d’afficher les résultats.

### ISSUE THREAD

**Issue by floshie-git** [Florent-Git/signal-processing-project#17]

**Comment by rafuryc** [comment]
Fait, cependant, ce sont 7 menu items vu qu'il y a 7 énoncés (je pense qu'il disait 8 car il voulait 2 items pour lenaAEgaliser, on fera les 2 méthodes dans le dialogue directement avec un sélecteur).
